use DBI;
my $table = shift;
my $database = shift;
my $user="root";
my $pass="mungyn1950";
my $driver="mysql";
my $db ="shareasale";
my $host="127.0.0.1";
my $port = "3307";
my $dsn="dbi:$driver:database=$db;host=$host;port=$port";
print "create table ";
print $table ;
print " ( ";
print "id int auto_increment primary key,\n";
print "productID text,\n";
print "name text,\n";
print "merchantID text,\n";
print "merchant  text  ,\n";
print "link text  ,\n";
print "thumbnail text,\n";
print "BigImage text,\n";
print "price text,\n";
print "retailPrice text,\n";
print "Category    text,\n";
print "description text,\n";
print " );\n";